blank_issues_enabled: true
contact_links:
  - name: Something else?
    url: https://github.com/toeverything/LoveNotes/discussions
    about: Feel free to ask and answer questions over in GitHub Discussions
  - name: LoveNotes Community Support
    url: https://community.lovenotes.pro
    about: LoveNotes Community - a place to ask, learn and engage with others
