[package]
edition = "2024"
name    = "lovenotes_native"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lovenotes_common = { workspace = true, features = ["hashcash"] }
lovenotes_media_capture = { path = "./media_capture" }
lovenotes_nbstore = { path = "./nbstore" }
lovenotes_sqlite_v1 = { path = "./sqlite_v1" }
napi = { workspace = true }
napi-derive = { workspace = true }
once_cell = { workspace = true }
sqlx = { workspace = true, default-features = false, features = [
  "chrono",
  "macros",
  "migrate",
  "runtime-tokio",
  "sqlite",
  "tls-rustls",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
chrono     = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
sqlx = { workspace = true, default-features = false, features = [
  "chrono",
  "json",
  "macros",
  "migrate",
  "runtime-tokio",
  "sqlite",
  "tls-rustls",
] }
tokio = { workspace = true, features = ["full"] }
